name: Tagged Custom Hotbar CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: .github/workflows/zip.sh
    - name: Update Version
      shell: bash
      id: set-version
      run: node ./.github/workflows/set-version.js ${{ github.ref }}
    - name: Create Release
      id: create_versioned_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./my-module.zip'
        tag: ${{ github.ref }} 
